/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.isched.gui;

import com.aldrin.isched.model.Schedule;

/**
 *
 * @author Java Programming with Aldrin
 */
public class JDialogConflictDetails extends javax.swing.JDialog {

    /**
     * Creates new form JDialogConflictDetails
     */
    private JFrameMain jFrameMain;
    private Schedule schedule;
    public JDialogConflictDetails(JFrameMain jFrameMain, boolean modal,Schedule schedule) {
        super(jFrameMain, modal);
        initComponents();
        this.schedule =schedule;
        jLabelInstructor.setText(schedule.getInstructor().getInstructor());
        jLabelSection.setText(schedule.getSection().getCode());
        jLabelSubject.setText(schedule.getSubject().getSubject());
        jLabelDay.setText(schedule.getDay().getDay());
        jLabelTime.setText(schedule.getTime().getTime());
        jLabelRoom.setText(schedule.getRoom().getRoom());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelDay = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelInstructor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelRoom = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelSection = new javax.swing.JLabel();
        jLabelSubject = new javax.swing.JLabel();
        jLabelInstructor5 = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jLabelInstructor7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONFLICT SCHEDULE");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ROOM:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 70, 26));

        jLabelDay.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDay.setOpaque(true);
        getContentPane().add(jLabelDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 186, 26));

        jLabel2.setText("INSTRUCTOR:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 26));

        jLabelInstructor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInstructor.setOpaque(true);
        getContentPane().add(jLabelInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 186, 26));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("SECTION:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 26));

        jLabelRoom.setBackground(new java.awt.Color(255, 255, 255));
        jLabelRoom.setOpaque(true);
        getContentPane().add(jLabelRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 186, 26));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("SUBJECT:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, 26));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("DAY:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, 26));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("TIME:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 70, 26));

        jLabelSection.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSection.setOpaque(true);
        getContentPane().add(jLabelSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 186, 26));

        jLabelSubject.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSubject.setOpaque(true);
        getContentPane().add(jLabelSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 186, 26));
        getContentPane().add(jLabelInstructor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 186, 26));

        jLabelTime.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTime.setOpaque(true);
        getContentPane().add(jLabelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 186, 26));
        getContentPane().add(jLabelInstructor7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 186, 26));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 80, 30));

        setSize(new java.awt.Dimension(324, 299));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDay;
    private javax.swing.JLabel jLabelInstructor;
    private javax.swing.JLabel jLabelInstructor5;
    private javax.swing.JLabel jLabelInstructor7;
    private javax.swing.JLabel jLabelRoom;
    private javax.swing.JLabel jLabelSection;
    private javax.swing.JLabel jLabelSubject;
    private javax.swing.JLabel jLabelTime;
    // End of variables declaration//GEN-END:variables
}
