/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aldrin.isched.gui;

import com.aldrin.isched.controller.AppController;
import com.aldrin.isched.dao.impl.ScheduleDAOImpl;
import com.aldrin.isched.dao.impl.SchoolYearDAOImpl;
import com.aldrin.isched.gui.dialog.JDialogCampusHead;
import com.aldrin.isched.gui.dialog.JDialogChangePassword;
import com.aldrin.isched.gui.dialog.JDialogDay;
import com.aldrin.isched.gui.dialog.JDialogInstructor;
import com.aldrin.isched.gui.dialog.JDialogRoom;
import com.aldrin.isched.gui.dialog.JDialogSchool;
import com.aldrin.isched.gui.dialog.JDialogSchoolYear;
import com.aldrin.isched.gui.dialog.JDialogSection;
import com.aldrin.isched.gui.dialog.JDialogSubject;
import com.aldrin.isched.gui.dialog.JDialogTime;
import com.aldrin.isched.gui.dialog.JDialogUserAccount;
import com.aldrin.isched.model.Day;
import com.aldrin.isched.model.Instructor;
import com.aldrin.isched.model.Room;
import com.aldrin.isched.model.Schedule;
import com.aldrin.isched.model.SchoolYear;
import com.aldrin.isched.model.Section;
import com.aldrin.isched.model.Subject;
import com.aldrin.isched.model.Time;
import com.aldrin.isched.model.UserAccount;
import com.aldrin.isched.reports.JDialogReportSchedule;
import com.aldrin.isched.util.ComboBoxList;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class JFrameMain extends javax.swing.JFrame implements MouseListener, ActionListener {

    private ScheduleDAOImpl scheduleDAOImpl = new ScheduleDAOImpl();
    private Schedule schedule = new Schedule();
    private UserAccount userAccount;

    public JFrameMain() {
        initComponents();
        ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"));
        setIconImage(icon.getImage());
        jTextFieldSearch.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Search");
        //icon
        jTextFieldSearch.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("svg/search.svg", 24, 24));
        comboBoxSchoolYear();
        setTable();
        ComboBoxList syId = (ComboBoxList) this.jComboBox1.getSelectedItem();
        selectSchedule(syId.getId());
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
//        jButtonDelete.setVisible(false);
        jComboBox1.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClassSchedule = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButtonNew = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonUpdate = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButtonDelete = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jTextFieldSearch = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanelToolBar = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButtonSubject = new javax.swing.JButton();
        jButtonSection = new javax.swing.JButton();
        jButtonDay = new javax.swing.JButton();
        jButtonTime = new javax.swing.JButton();
        jButtonRoom = new javax.swing.JButton();
        jButtonInstructor = new javax.swing.JButton();
        jButtonSemester = new javax.swing.JButton();
        jButtonSummary = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUser = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuManage = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("iSched v1.0");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        jTableClassSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableClassSchedule);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel7.setPreferredSize(new java.awt.Dimension(5, 599));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7, java.awt.BorderLayout.WEST);

        jPanel8.setPreferredSize(new java.awt.Dimension(5, 599));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, java.awt.BorderLayout.EAST);

        jPanel9.setPreferredSize(new java.awt.Dimension(1369, 50));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonNew.setIcon(new FlatSVGIcon("svg/add.svg",24,24));
        jButtonNew.setText("NEW");
        jButtonNew.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonNew.setPreferredSize(new java.awt.Dimension(80, 40));
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonNew);

        jPanel3.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel3);

        jButtonUpdate.setIcon(new FlatSVGIcon("svg/edit.svg",24,24));
        jButtonUpdate.setText("UPDATE");
        jButtonUpdate.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonUpdate.setPreferredSize(new java.awt.Dimension(80, 40));
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonUpdate);

        jPanel14.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel14);

        jButtonDelete.setIcon(new FlatSVGIcon("svg/delete.svg",24,24));
        jButtonDelete.setText("DELETE");
        jButtonDelete.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonDelete.setPreferredSize(new java.awt.Dimension(80, 40));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel9.add(jButtonDelete);

        jPanel4.add(jPanel9, java.awt.BorderLayout.SOUTH);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setPreferredSize(new java.awt.Dimension(1369, 40));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });
        jPanel10.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 5, 268, 30));

        jLabel2.setText("SCHOOL YEAR:");
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, 30));

        jPanel5.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel11.setPreferredSize(new java.awt.Dimension(400, 40));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 5));

        jTextFieldSearch.setPreferredSize(new java.awt.Dimension(250, 32));
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyReleased(evt);
            }
        });
        jPanel12.add(jTextFieldSearch);

        jPanel11.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel13.setPreferredSize(new java.awt.Dimension(5, 40));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel13, java.awt.BorderLayout.EAST);

        jPanel5.add(jPanel11, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanelToolBar.setOpaque(false);
        jPanelToolBar.setPreferredSize(new java.awt.Dimension(1369, 65));
        jPanelToolBar.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);
        jToolBar1.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new FlatSVGIcon("svg/schedule.svg",42,42));
        jButton1.setText("Schedule");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton1.setMaximumSize(new java.awt.Dimension(48, 70));
        jButton1.setMinimumSize(new java.awt.Dimension(48, 70));
        jButton1.setPreferredSize(new java.awt.Dimension(48, 70));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButtonSubject.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSubject.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        jButtonSubject.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSubject.setIcon(new FlatSVGIcon("svg/subject.svg",42,42));
        jButtonSubject.setText("Subject");
        jButtonSubject.setToolTipText("Subject");
        jButtonSubject.setFocusable(false);
        jButtonSubject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSubject.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonSubject.setMaximumSize(new java.awt.Dimension(48, 70));
        jButtonSubject.setMinimumSize(new java.awt.Dimension(48, 70));
        jButtonSubject.setPreferredSize(new java.awt.Dimension(48, 70));
        jButtonSubject.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubjectActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSubject);

        jButtonSection.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSection.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        jButtonSection.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSection.setIcon(new FlatSVGIcon("svg/section.svg",42,42));
        jButtonSection.setText("Section");
        jButtonSection.setToolTipText("Section");
        jButtonSection.setFocusable(false);
        jButtonSection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSection.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonSection.setMaximumSize(new java.awt.Dimension(48, 70));
        jButtonSection.setMinimumSize(new java.awt.Dimension(48, 70));
        jButtonSection.setPreferredSize(new java.awt.Dimension(48, 70));
        jButtonSection.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSectionActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSection);

        jButtonDay.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDay.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        jButtonDay.setForeground(new java.awt.Color(51, 51, 51));
        jButtonDay.setIcon(new FlatSVGIcon("svg/day.svg",42,42));
        jButtonDay.setText("Day");
        jButtonDay.setToolTipText("Day");
        jButtonDay.setFocusable(false);
        jButtonDay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDay.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonDay.setMaximumSize(new java.awt.Dimension(48, 70));
        jButtonDay.setMinimumSize(new java.awt.Dimension(48, 70));
        jButtonDay.setPreferredSize(new java.awt.Dimension(48, 70));
        jButtonDay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDayActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonDay);

        jButtonTime.setBackground(new java.awt.Color(204, 204, 204));
        jButtonTime.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        jButtonTime.setForeground(new java.awt.Color(51, 51, 51));
        jButtonTime.setIcon(new FlatSVGIcon("svg/clock.svg",42,42));
        jButtonTime.setText("Time");
        jButtonTime.setToolTipText("Time");
        jButtonTime.setFocusable(false);
        jButtonTime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTime.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonTime.setMaximumSize(new java.awt.Dimension(48, 70));
        jButtonTime.setMinimumSize(new java.awt.Dimension(48, 70));
        jButtonTime.setPreferredSize(new java.awt.Dimension(48, 70));
        jButtonTime.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimeActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonTime);

        jButtonRoom.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRoom.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        jButtonRoom.setForeground(new java.awt.Color(51, 51, 51));
        jButtonRoom.setIcon(new FlatSVGIcon("svg/room.svg",42,42));
        jButtonRoom.setText("Room");
        jButtonRoom.setToolTipText("Room");
        jButtonRoom.setFocusable(false);
        jButtonRoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRoom.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonRoom.setMaximumSize(new java.awt.Dimension(48, 70));
        jButtonRoom.setMinimumSize(new java.awt.Dimension(48, 70));
        jButtonRoom.setPreferredSize(new java.awt.Dimension(48, 70));
        jButtonRoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRoomActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonRoom);

        jButtonInstructor.setBackground(new java.awt.Color(204, 204, 204));
        jButtonInstructor.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        jButtonInstructor.setForeground(new java.awt.Color(51, 51, 51));
        jButtonInstructor.setIcon(new FlatSVGIcon("svg/teacher.svg",42,42));
        jButtonInstructor.setText("Instructor");
        jButtonInstructor.setToolTipText("Professor/Instructor");
        jButtonInstructor.setFocusable(false);
        jButtonInstructor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInstructor.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonInstructor.setMaximumSize(new java.awt.Dimension(48, 70));
        jButtonInstructor.setMinimumSize(new java.awt.Dimension(48, 70));
        jButtonInstructor.setPreferredSize(new java.awt.Dimension(48, 70));
        jButtonInstructor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstructorActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonInstructor);

        jButtonSemester.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSemester.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        jButtonSemester.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSemester.setIcon(new FlatSVGIcon("svg/calendar.svg",42,42));
        jButtonSemester.setText("SY");
        jButtonSemester.setToolTipText("School Year");
        jButtonSemester.setFocusable(false);
        jButtonSemester.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSemester.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonSemester.setMaximumSize(new java.awt.Dimension(48, 70));
        jButtonSemester.setMinimumSize(new java.awt.Dimension(48, 70));
        jButtonSemester.setPreferredSize(new java.awt.Dimension(48, 70));
        jButtonSemester.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSemesterActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSemester);

        jButtonSummary.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSummary.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        jButtonSummary.setForeground(new java.awt.Color(51, 51, 51));
        jButtonSummary.setIcon(new FlatSVGIcon("svg/report.svg",42,42));
        jButtonSummary.setText("Report");
        jButtonSummary.setToolTipText("Summary of teaching load");
        jButtonSummary.setFocusable(false);
        jButtonSummary.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSummary.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonSummary.setMaximumSize(new java.awt.Dimension(48, 70));
        jButtonSummary.setMinimumSize(new java.awt.Dimension(48, 70));
        jButtonSummary.setPreferredSize(new java.awt.Dimension(48, 70));
        jButtonSummary.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSummaryActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSummary);

        jPanelToolBar.add(jToolBar1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelToolBar, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuUser.setText("File");

        jMenuItem10.setText("Change Password");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItem10);

        jMenuItem11.setText("Logout");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItem11);
        jMenuUser.add(jSeparator1);

        jMenuItem12.setText("Exit");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItem12);

        jMenuBar1.add(jMenuUser);

        jMenu2.setText("Setup");

        jMenuItem1.setText("Day");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Time");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Room");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem6.setText("Subject");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem4.setText("Instructor");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Section");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem7.setText("School Year");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenuManage.setText("Manage");

        jMenuItem8.setText("Campus Head");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenuManage.add(jMenuItem8);

        jMenuItem9.setText("School");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenuManage.add(jMenuItem9);

        jMenuItem16.setText("User");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenuManage.add(jMenuItem16);

        jMenuBar1.add(jMenuManage);

        jMenu5.setText("Theme");

        jMenuItem14.setText("Light");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuItem15.setText("Dark");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Help");

        jMenuItem13.setText("About");
        jMenu4.add(jMenuItem13);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1385, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JDialogDay day = new JDialogDay(this, true);
        day.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JDialogTime time = new JDialogTime(this, true);
        time.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JDialogRoom room = new JDialogRoom(this, true);
        room.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JDialogSubject subject = new JDialogSubject(this, true);
        subject.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        JDialogSchoolYear schoolYear = new JDialogSchoolYear(this, true);
        schoolYear.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JDialogInstructor instructor = new JDialogInstructor(this, true);
        instructor.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JDialogSection section = new JDialogSection(this, true);
        section.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        JDialogCampusHead campusHead = new JDialogCampusHead(this, true);
        campusHead.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        JDialogSchool school = new JDialogSchool(this, true);
        school.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jTextFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyReleased
        String text = jTextFieldSearch.getText().trim();
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text + ",*"));
        }
    }//GEN-LAST:event_jTextFieldSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JDialogClassSchedule schedule = new JDialogClassSchedule(this, true);
        schedule.setVisible(true);
        ComboBoxList syId = (ComboBoxList) this.jComboBox1.getSelectedItem();
        selectSchedule(syId.getId());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(new FlatLightLaf());
                SwingUtilities.updateComponentTreeUI(this);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(new FlatDarkLaf());
                SwingUtilities.updateComponentTreeUI(this);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        JDialogClassSchedule sched = new JDialogClassSchedule(this, true, schedule, "Update");
        sched.setVisible(true);
        ComboBoxList syId = (ComboBoxList) this.jComboBox1.getSelectedItem();
        selectSchedule(syId.getId());
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimeActionPerformed
        JDialogTime time = new JDialogTime(this, true);
        time.setVisible(true);
    }//GEN-LAST:event_jButtonTimeActionPerformed

    private void jButtonDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDayActionPerformed
        JDialogDay day = new JDialogDay(this, true);
        day.setVisible(true);
    }//GEN-LAST:event_jButtonDayActionPerformed

    private void jButtonRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRoomActionPerformed
        JDialogRoom room = new JDialogRoom(this, true);
        room.setVisible(true);
    }//GEN-LAST:event_jButtonRoomActionPerformed

    private void jButtonInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstructorActionPerformed
        JDialogInstructor instructor = new JDialogInstructor(this, true);
        instructor.setVisible(true);
    }//GEN-LAST:event_jButtonInstructorActionPerformed

    private void jButtonSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSectionActionPerformed
        JDialogSection section = new JDialogSection(this, true);
        section.setVisible(true);
    }//GEN-LAST:event_jButtonSectionActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        JDialogClassSchedule schedule = new JDialogClassSchedule(this, true);
        schedule.setVisible(true);
        ComboBoxList syId = (ComboBoxList) this.jComboBox1.getSelectedItem();
        selectSchedule(syId.getId());
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubjectActionPerformed
        JDialogSubject subject = new JDialogSubject(this, true);
        subject.setVisible(true);
        comboBoxSchoolYear();
    }//GEN-LAST:event_jButtonSubjectActionPerformed

    private void jButtonSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSemesterActionPerformed
        JDialogSchoolYear schoolYear = new JDialogSchoolYear(this, true);
        schoolYear.setVisible(true);
        comboBoxSchoolYear();
    }//GEN-LAST:event_jButtonSemesterActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        JDialogClassSchedule sched = new JDialogClassSchedule(this, true, schedule, "Delete");
        sched.setVisible(true);
        ComboBoxList syId = (ComboBoxList) this.jComboBox1.getSelectedItem();
        selectSchedule(syId.getId());
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSummaryActionPerformed
        JDialogReportSchedule report = new JDialogReportSchedule(this, true);
        report.setVisible(true);
    }//GEN-LAST:event_jButtonSummaryActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        JDialogUserAccount user = new JDialogUserAccount(this, true);
        user.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        this.dispose();
        new AppController(new JFrameLogin());
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        JDialogChangePassword changePassword = new JDialogChangePassword(this, true, userAccount);
        changePassword.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained

    }//GEN-LAST:event_jComboBox1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDay;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInstructor;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonRoom;
    private javax.swing.JButton jButtonSection;
    private javax.swing.JButton jButtonSemester;
    private javax.swing.JButton jButtonSubject;
    private javax.swing.JButton jButtonSummary;
    private javax.swing.JButton jButtonTime;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<Object> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMenuManage;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelToolBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTableClassSchedule;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    private SchoolYearDAOImpl schoolYearDAOImpl = new SchoolYearDAOImpl();

    private void comboBoxSchoolYear() {
        schoolYearDAOImpl.comboBoxSchoolYear();
        jComboBox1.removeAllItems();
        for (ComboBoxList a : schoolYearDAOImpl.getList()) {
            this.jComboBox1.addItem(a);
        }
    }
    public DefaultTableModel tableModel = new DefaultTableModel(new Object[]{"SCHEDULE ID", "INSTRUCTOR_ID", "SUBJECT_ID", "SECTION_ID", "DAY_ID", "TIME_ID",
        "ROOM_ID", "SCHOOL_YEAR_ID", "INSTRUCTOR", "SECTION", "SUBJECT", "DAY", "TIME", "ROOM", "UNIT"}, 0) {
        public Class getColumnClass(int columnIndex) {
            if (columnIndex == 0) {
                return String.class;
            }
            switch (columnIndex) {
                case 1:
                    return Integer.class;
                case 2:
                    return String.class;
                case 3:
                    return String.class;
                case 4:
                    return String.class;
                case 5:
                    return String.class;
                case 6:
                    return String.class;
                case 7:
                    return String.class;
                default:
                    return String.class;
            }
        }

        public boolean isCellEditable(int row, int col) {
            if (col < 10) {
                return false;

            } else {
                return true;
            }
        }
    };
    private TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tableModel);

    private void setTable() {
        jTableClassSchedule.setCellSelectionEnabled(true);
        jTableClassSchedule = new JTable(tableModel);
        jScrollPane1.setViewportView(jTableClassSchedule);
        jTableClassSchedule.addMouseListener(this);
        jTableClassSchedule.setRowSorter(sorter);
        TableColumn hide0 = jTableClassSchedule.getColumnModel().getColumn(0);
        hide0.setMinWidth(0);
        hide0.setMaxWidth(0);
        hide0.setPreferredWidth(0);
        TableColumn hide1 = jTableClassSchedule.getColumnModel().getColumn(1);
        hide1.setMinWidth(0);
        hide1.setMaxWidth(0);
        hide1.setPreferredWidth(0);
        TableColumn hide2 = jTableClassSchedule.getColumnModel().getColumn(2);
        hide2.setMinWidth(0);
        hide2.setMaxWidth(0);
        hide2.setPreferredWidth(0);
        TableColumn hide3 = jTableClassSchedule.getColumnModel().getColumn(3);
        hide3.setMinWidth(0);
        hide3.setMaxWidth(0);
        hide3.setPreferredWidth(0);
        TableColumn hide4 = jTableClassSchedule.getColumnModel().getColumn(4);
        hide4.setMinWidth(0);
        hide4.setMaxWidth(0);
        hide4.setPreferredWidth(0);
        TableColumn hide5 = jTableClassSchedule.getColumnModel().getColumn(5);
        hide5.setMinWidth(0);
        hide5.setMaxWidth(0);
        hide5.setPreferredWidth(0);
        TableColumn hide6 = jTableClassSchedule.getColumnModel().getColumn(6);
        hide6.setMinWidth(0);
        hide6.setMaxWidth(0);
        hide6.setPreferredWidth(0);
        TableColumn hide7 = jTableClassSchedule.getColumnModel().getColumn(7);
        hide7.setMinWidth(0);
        hide7.setMaxWidth(0);
        hide7.setPreferredWidth(0);

        TableColumn[] column = new TableColumn[100];
        column[1] = jTableClassSchedule.getColumnModel().getColumn(1);
        column[1].setPreferredWidth(30);

        column[2] = jTableClassSchedule.getColumnModel().getColumn(2);
        column[2].setPreferredWidth(80);

        column[3] = jTableClassSchedule.getColumnModel().getColumn(3);
        column[3].setPreferredWidth(220);

        column[4] = jTableClassSchedule.getColumnModel().getColumn(4);
        column[4].setPreferredWidth(160);

        column[5] = jTableClassSchedule.getColumnModel().getColumn(5);
        column[5].setPreferredWidth(60);

        column[6] = jTableClassSchedule.getColumnModel().getColumn(6);
        column[6].setPreferredWidth(60);

        column[8] = jTableClassSchedule.getColumnModel().getColumn(8);
        column[8].setPreferredWidth(260);

        column[11] = jTableClassSchedule.getColumnModel().getColumn(11);
        column[11].setPreferredWidth(60);

    }

    @Override
    public void mouseClicked(MouseEvent e) {
        if (e.getSource() == jTableClassSchedule) {
            if (e.getButton() == MouseEvent.BUTTON1) {
                if (e.getClickCount() == 1) {
                    int row = jTableClassSchedule.getSelectedRow();
                    if (row != -1) {
//      SCHEDULE.ID,1INSTRUCTOR_ID,2SUBJECT_ID,3SECTION_ID,DAY_ID,TIME_ID,ROOM_ID,SCHOOL_YEAR_ID, 
                        Long scheduleId = Long.parseLong(jTableClassSchedule.getValueAt(row, 0).toString());
                        Long instructorId = Long.parseLong(jTableClassSchedule.getValueAt(row, 1).toString());
                        Long subjectId = Long.parseLong(jTableClassSchedule.getValueAt(row, 2).toString());
                        Long sectionId = Long.parseLong(jTableClassSchedule.getValueAt(row, 3).toString());
                        Long dayId = Long.parseLong(jTableClassSchedule.getValueAt(row, 4).toString());
                        Long timeId = Long.parseLong(jTableClassSchedule.getValueAt(row, 5).toString());
                        Long roomId = Long.parseLong(jTableClassSchedule.getValueAt(row, 6).toString());
                        Long schoolYeaarId = Long.parseLong(jTableClassSchedule.getValueAt(row, 7).toString());
                        Schedule schedule = new Schedule();
                        schedule.setId(scheduleId);//0
                        Instructor instructor = new Instructor();
                        instructor.setId(instructorId);//1
                        Subject subject = new Subject();
                        subject.setId(subjectId);//2
                        Section section = new Section();
                        section.setId(sectionId);//3
                        Day day = new Day();
                        day.setId(dayId);//4
                        Time time = new Time();
                        time.setId(timeId);//5
                        Room room = new Room();
                        room.setId(roomId);//6
                        SchoolYear schoolYear = new SchoolYear();
                        schoolYear.setId(schoolYeaarId);//7
                        schedule.setInstructor(instructor);
                        schedule.setSubject(subject);
                        schedule.setSection(section);
                        schedule.setDay(day);
                        schedule.setTime(time);
                        schedule.setRoom(room);
                        schedule.setSchoolYear(schoolYear);
                        this.schedule = schedule;

                        jButtonUpdate.setEnabled(true);
                        jButtonDelete.setEnabled(true);

                    }
                }
            }
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }

    private ArrayList<Schedule> scheduleList;
// " SCHEDULE.ID,INSTRUCTOR_ID,SUBJECT_ID,SECTION_ID,DAY_ID,TIME_ID,ROOM_ID,SCHOOL_YEAR_ID, 
// ,"#",  "SECTION", "SUBJECT", "INSTRUCTOR", "DAY", "TIME", "ROOM","UNITS"

    private void selectSchedule(Long syId) {
        tableModel.setRowCount(0);
        scheduleList = scheduleDAOImpl.selectSchedule(syId);
        tableModel.setRowCount(0);
        for (Schedule s : scheduleList) {
            tableModel.addRow(new Object[]{s.getId(), s.getInstructor().getId(), s.getSubject().getId(), s.getSection().getId(),
                s.getDay().getId(), s.getTime().getId(), s.getRoom().getId(), s.getSchoolYear().getId(),
                s.getInstructor().getInstructor(), s.getSection().getCode(), s.getSubject().getSubject(),
                s.getDay().getDay(), s.getTime().getTime(), s.getRoom().getRoom(), s.getSubject().getUnit()});
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == jComboBox1) {
           if (jComboBox1.getItemCount() == 0)  {
//                comboBoxSchoolYear();
                return;
            } else {
                ComboBoxList syId = (ComboBoxList) this.jComboBox1.getSelectedItem();
                selectSchedule(syId.getId());
            }
        }
    }

    /**
     * @return the jMenuManage
     */
    

    public javax.swing.JMenu getjMenuManage() {
        return jMenuManage;
    }

    /**
     * @param jMenuManage the jMenuManage to set
     */
    public void setjMenuManage(javax.swing.JMenu jMenuManage) {
        this.jMenuManage = jMenuManage;
    }

    /**
     * @return the jMenuUser
     */
    public javax.swing.JMenu getjMenuUser() {
        return jMenuUser;
    }

    /**
     * @param jMenuUser the jMenuUser to set
     */
    public void setjMenuUser(javax.swing.JMenu jMenuUser) {
        this.jMenuUser = jMenuUser;
    }

    /**
     * @return the userAccount
     */
    public UserAccount getUserAccount() {
        return userAccount;
    }

    /**
     * @param userAccount the userAccount to set
     */
    public void setUserAccount(UserAccount userAccount) {
        this.userAccount = userAccount;
    }

}
