/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.isched.gui.dialog.au;

import com.aldrin.isched.dao.impl.CampusHeadDAOImpl;
import com.aldrin.isched.dao.impl.SchoolYearDAOImpl;
import com.aldrin.isched.gui.JFrameMain;
import com.aldrin.isched.model.CampusHead;
import com.aldrin.isched.model.SchoolYear;
import com.aldrin.isched.model.Semester;
import com.aldrin.isched.util.ComboBoxList;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ALDRIN B. C.
 */
public class JDialogCampusHeadAU extends javax.swing.JDialog {

    private JFrameMain jFrameRegister;
    private CampusHead campusHead = new CampusHead();
    static String title;
    private Semester semester = new Semester();
    private CampusHeadDAOImpl campusHeadDAOImpl = new CampusHeadDAOImpl();

    public JDialogCampusHeadAU(JFrameMain jFrameMain, boolean modal) {
        super(jFrameMain, modal);
        initComponents();
        setTitle("New");
        this.title = "New";
        jButton1.setIcon(new FlatSVGIcon("svg/save.svg", 24, 24));
        jTextFieldCampusHead.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "CAMPUS HEAD");
        jTextFieldCampusHead.setText(campusHead.getCampusHead());
        jTextFieldSateliteDirector.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "SATELITE DIRECTOR");
        jTextFieldSateliteDirector.setText(campusHead.getSateliteDirector());
        jTextFieldVPAA.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "VPAA");
        jTextFieldVPAA.setText(campusHead.getVpaa());
        comboBoxSchooLYear();
        jCheckBoxActive.setSelected(true);

    }

    public JDialogCampusHeadAU(JFrameMain jFrameMain, boolean modal, CampusHead campusHead, String title) {
        super(jFrameMain, modal);
        initComponents();
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(187, 187, 187));
        setTitle(title);
        comboBoxSchooLYear();
        this.title = title;
        this.campusHead = campusHead;
        jButton1.setIcon(new FlatSVGIcon("svg/edit.svg", 24, 24));
        jButton1.setText(title);
        jTextFieldCampusHead.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "CAMPUS HEAD");
        jTextFieldCampusHead.setText(campusHead.getCampusHead());
        jTextFieldSateliteDirector.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "SATELITE DIRECTOR");
        jTextFieldSateliteDirector.setText(campusHead.getSateliteDirector());
        jTextFieldVPAA.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "VPAA");
        jTextFieldVPAA.setText(campusHead.getVpaa());
        jCheckBoxActive.setSelected(campusHead.getActive());
        for (ComboBoxList a : this.schoolYearDAOImpl.getList()) {
            a.setSelectedId(schoolYearDAOImpl.getList(), String.valueOf(campusHead.getSchoolYear().getId()), jComboBoxSchoolYear);
        }
    }

    public JDialogCampusHeadAU(JFrameMain jFrameMain, boolean modal, String title, CampusHead campusHead) {
        super(jFrameMain, modal);
        initComponents();
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(187, 187, 187));
        setTitle(title);
        comboBoxSchooLYear();
        this.campusHead = campusHead;
        this.title = title;
        jButton1.setIcon(new FlatSVGIcon("svg/delete.svg", 24, 24));
        jButton1.setText(title);
        jTextFieldCampusHead.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "CAMPUS HEAD");
        jTextFieldCampusHead.setText(campusHead.getCampusHead());
        jTextFieldSateliteDirector.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "SATELITE DIRECTOR");
        jTextFieldSateliteDirector.setText(campusHead.getSateliteDirector());
        jTextFieldVPAA.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "VPAA");
        jTextFieldVPAA.setText(campusHead.getVpaa());
        jCheckBoxActive.setSelected(campusHead.getActive());
        for (ComboBoxList a : this.schoolYearDAOImpl.getList()) {
            a.setSelectedId(schoolYearDAOImpl.getList(), String.valueOf(campusHead.getSchoolYear().getId()), jComboBoxSchoolYear);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldVPAA = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBoxSchoolYear = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCampusHead = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSateliteDirector = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCheckBoxActive = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextFieldVPAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 290, 30));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 140, 30));

        getContentPane().add(jComboBoxSchoolYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 290, 30));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("SCHOOL YEAR:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("CAMPUS HEAD:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 30));
        getContentPane().add(jTextFieldCampusHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 290, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("SATELITE DIRECTOR:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 30));
        getContentPane().add(jTextFieldSateliteDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 290, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("VPAA:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, 30));

        jCheckBoxActive.setText("ACTIVE");
        jCheckBoxActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActiveActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 290, -1));

        setSize(new java.awt.Dimension(438, 351));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.title.equals("New")) {
            int response = JOptionPane.showConfirmDialog(jFrameRegister, "Are you sure to save  ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.campusHead.setId(null);
                this.campusHead.setCampusHead(jTextFieldCampusHead.getText());
                this.campusHead.setSateliteDirector(jTextFieldSateliteDirector.getText());
                this.campusHead.setVpaa(jTextFieldVPAA.getText());
                ComboBoxList syId = (ComboBoxList) this.jComboBoxSchoolYear.getSelectedItem();
                SchoolYear sy = new SchoolYear();
                sy.setId(syId.getId());
                this.campusHead.setSchoolYear(sy);
                this.campusHead.setActive(jCheckBoxActive.isSelected());
                this.campusHeadDAOImpl.inActiveCampusHead();//in active all campus head
                this.campusHeadDAOImpl.addCampusHead(campusHead);
                this.dispose();
            }
        } else if (this.title.equals("Update")) {
            int response = JOptionPane.showConfirmDialog(jFrameRegister, "Are you sure to update  ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.campusHead.setCampusHead(jTextFieldCampusHead.getText());
                this.campusHead.setSateliteDirector(jTextFieldSateliteDirector.getText());
                this.campusHead.setVpaa(jTextFieldVPAA.getText());
                ComboBoxList syId = (ComboBoxList) this.jComboBoxSchoolYear.getSelectedItem();
                SchoolYear sy = new SchoolYear();
                sy.setId(syId.getId());
                this.campusHead.setSchoolYear(sy);
                this.campusHead.setActive(jCheckBoxActive.isSelected());
                this.campusHeadDAOImpl.updateCampusHead(campusHead);
                this.dispose();
            }
        } else if (this.title.equals("Delete")) {
            int response = JOptionPane.showConfirmDialog(jFrameRegister, "Are you sure to delete " + jTextFieldVPAA.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.campusHeadDAOImpl.deleteCampusHead(campusHead);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxActiveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxActive;
    private javax.swing.JComboBox<Object> jComboBoxSchoolYear;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldCampusHead;
    private javax.swing.JTextField jTextFieldSateliteDirector;
    private javax.swing.JTextField jTextFieldVPAA;
    // End of variables declaration//GEN-END:variables
    private SchoolYearDAOImpl schoolYearDAOImpl = new SchoolYearDAOImpl();
    
    private void comboBoxSchooLYear() {
        schoolYearDAOImpl.comboBoxSchoolYear();
        jComboBoxSchoolYear.removeAllItems();
        for (ComboBoxList a : schoolYearDAOImpl.getList()) {
            this.jComboBoxSchoolYear.addItem(a);
        }
    }

}
