/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.isched.gui.dialog.au;

import com.aldrin.isched.dao.impl.TimeDAOImpl;
import com.aldrin.isched.gui.JFrameMain;
import com.aldrin.isched.model.Time;
import com.aldrin.isched.util.TimeValidator;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ALDRIN B. C.
 */
public class JDialogTimeAU extends javax.swing.JDialog {

    /**
     * Creates new form JDialogCourseAU
     */
    private JFrameMain jFrameMain;
    private Time time = new Time();
    static String title;
    private TimeDAOImpl timeDAOImpl = new TimeDAOImpl();

    public JDialogTimeAU(JFrameMain jFrameMain, boolean modal) {
        super(jFrameMain, modal);
        initComponents();
        setTitle("New");
        this.title = "New";
        jButton1.setIcon(new FlatSVGIcon("svg/save.svg", 24, 24));
        jTextFieldTime.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "TIME");
        jTextFieldTime.setText(time.getTime());
        jButton1.setEnabled(false);

    }

    public JDialogTimeAU(JFrameMain jFrameMain, boolean modal, Time time, String title) {
        super(jFrameMain, modal);
        initComponents();
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(187, 187, 187));
        setTitle(title);
        this.title = title;
        this.time = time;
        jButton1.setIcon(new FlatSVGIcon("svg/edit.svg", 24, 24));
        jButton1.setText(title);
        jTextFieldTime.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "TIME");
        jTextFieldTime.setText(this.time.getTime());
        jButton1.setEnabled(false);
    }

    public JDialogTimeAU(JFrameMain jFrameMain, boolean modal, String title, Time time) {
        super(jFrameMain, modal);
        initComponents();
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(187, 187, 187));
        setTitle(title);
        this.time = time;
        this.title = title;
        jButton1.setIcon(new FlatSVGIcon("svg/delete.svg", 24, 24));
        jButton1.setText(title);
        jTextFieldTime.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "TIME");
        jTextFieldTime.setText(time.getTime());
        jButton1.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldTime = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("TIME:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, 30));

        jTextFieldTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldTimeKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 250, 30));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 140, 30));

        jLabelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 330, 30));

        setSize(new java.awt.Dimension(366, 209));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TimeValidator tv = new TimeValidator(jTextFieldTime.getText());
        time.setStartTime(tv.getStartTime());
        time.setEndTime(tv.getEndTime());
        if (this.title.equals("New")) {
            int response = JOptionPane.showConfirmDialog(jFrameMain, "Are you sure to save " + jTextFieldTime.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.time.setId(null);
                this.time.setTime(jTextFieldTime.getText());
                timeDAOImpl.addTime(time);
                this.dispose();
            }
        } else if (this.title.equals("Update")) {
            int response = JOptionPane.showConfirmDialog(jFrameMain, "Are you sure to update " + jTextFieldTime.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.time.setTime(jTextFieldTime.getText());
                timeDAOImpl.updateTime(time);
                this.dispose();
            }
        } else if (this.title.equals("Delete")) {
            int response = JOptionPane.showConfirmDialog(jFrameMain, "Are you sure to delete " + jTextFieldTime.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                timeDAOImpl.deleteTime(time);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldTimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTimeKeyReleased
        if ((timeDAOImpl.isDuplicate(jTextFieldTime.getText()) == true)) {
            jLabelMessage.setText("Duplicate subjects are not allowed!");
            jTextFieldTime.putClientProperty("JComponent.outline", "error");
            jButton1.setEnabled(false);
        } else if ((jTextFieldTime.getText().isEmpty())) {
            jLabelMessage.setText("Subject is required!");
            jTextFieldTime.putClientProperty("JComponent.outline", "error");
            jButton1.setEnabled(false);
        } else {
            jTextFieldTime.putClientProperty("JComponent.outline", null);
            jButton1.setEnabled(true);
            jLabelMessage.setText("");
        }
    }//GEN-LAST:event_jTextFieldTimeKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JTextField jTextFieldTime;
    // End of variables declaration//GEN-END:variables

    private Integer amPmHours(String time) {
        Integer hour = null;
        String start = time.substring(0, 5);
        String end = time.substring(6, 11);
        String amPm = time.substring(12, 14);

        return hour;
    }
}
