/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.isched.gui.dialog.au;

import com.aldrin.isched.dao.impl.SubjectDAOImpl;
import com.aldrin.isched.gui.JFrameMain;
import com.aldrin.isched.model.Subject;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ALDRIN B. C.
 */
public class JDialogSubjectAU extends javax.swing.JDialog {

    private JFrameMain jFrameMain;
    private Subject subject = new Subject();
    static String title;
    private SubjectDAOImpl subjectDAOImpl = new SubjectDAOImpl();

    public JDialogSubjectAU(JFrameMain jFrameRegister, boolean modal) {
        super(jFrameRegister, modal);
        initComponents();
        setTitle("New");
        this.title = "New";
        jButtonSave.setIcon(new FlatSVGIcon("svg/save.svg", 24, 24));
        jTextFieldSubject.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "SUBJECT");
        jTextFieldUnit.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "UNIT");
        jButtonSave.setEnabled(false);

    }

    public JDialogSubjectAU(JFrameMain jFrameMain, boolean modal, Subject subject, String title) {
        super(jFrameMain, modal);
        initComponents();
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(187, 187, 187));
        setTitle(title);
        this.title = title;
        this.subject = subject;
        jButtonSave.setIcon(new FlatSVGIcon("svg/edit.svg", 24, 24));
        jButtonSave.setText(title);
        jTextFieldSubject.setText(subject.getSubject());
        jTextFieldUnit.setText(String.valueOf(subject.getUnit()));
        jTextFieldSubject.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "SUBJECT");
        jTextFieldUnit.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "UNIT");
        jButtonSave.setEnabled(false);
    }

    public JDialogSubjectAU(JFrameMain jFrameMain, boolean modal, String title, Subject subject) {
        super(jFrameMain, modal);
        initComponents();
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(187, 187, 187));
        setTitle(title);
        this.subject = subject;
        this.title = title;
        jButtonSave.setIcon(new FlatSVGIcon("svg/delete.svg", 24, 24));
        jButtonSave.setText(title);
        jTextFieldSubject.setText(subject.getSubject());
        jTextFieldUnit.setText(String.valueOf(subject.getUnit()));
        jTextFieldSubject.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "SUBJECT");
        jTextFieldUnit.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "UNIT");
        jButtonSave.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUnit = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSubject = new javax.swing.JTextField();
        jLabelMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextFieldUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 250, 30));

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 140, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("UNIT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 100, 80, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("SUBJECT:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 60, 80, 30));

        jTextFieldSubject.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSubjectKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 250, 30));

        jLabelMessage.setForeground(new java.awt.Color(204, 0, 0));
        jLabelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 30));

        setSize(new java.awt.Dimension(366, 239));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if (this.title.equals("New")) {

            int response = JOptionPane.showConfirmDialog(jFrameMain, "Are you sure to save " + jTextFieldSubject.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.subject.setId(null);
                this.subject.setSubject(jTextFieldSubject.getText());
                this.subject.setUnit(Integer.parseInt(jTextFieldUnit.getText()));
                subjectDAOImpl.addSubject(subject);
                this.dispose();
            }
        } else if (this.title.equals("Update")) {
            int response = JOptionPane.showConfirmDialog(jFrameMain, "Are you sure to update " + jTextFieldSubject.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.subject.setSubject(jTextFieldSubject.getText());
                this.subject.setUnit(Integer.parseInt(jTextFieldUnit.getText()));
                subjectDAOImpl.updateSubject(subject);
                this.dispose();
            }
        } else if (this.title.equals("Delete")) {
            int response = JOptionPane.showConfirmDialog(jFrameMain, "Are you sure to delete " + jTextFieldSubject.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                subjectDAOImpl.deleteSubject(subject);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTextFieldSubjectKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSubjectKeyReleased
        if ((subjectDAOImpl.isDuplicate(jTextFieldSubject.getText()) == true)) {
            jLabelMessage.setText("Duplicate subjects are not allowed!");
            jTextFieldSubject.putClientProperty("JComponent.outline", "error");
            jButtonSave.setEnabled(false);
        } else if ((jTextFieldSubject.getText().isEmpty())) {
            jLabelMessage.setText("Subject is required!");
            jTextFieldSubject.putClientProperty("JComponent.outline", "error");
            jButtonSave.setEnabled(false);
        } else {
            jTextFieldSubject.putClientProperty("JComponent.outline", null);
            jButtonSave.setEnabled(true);
            jLabelMessage.setText("");
        }
    }//GEN-LAST:event_jTextFieldSubjectKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JTextField jTextFieldSubject;
    private javax.swing.JTextField jTextFieldUnit;
    // End of variables declaration//GEN-END:variables
}
