/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.isched.gui.dialog.au;

import com.aldrin.isched.dao.impl.SchoolYearDAOImpl;
import com.aldrin.isched.dao.impl.SemesterDAOImpl;
import com.aldrin.isched.gui.JFrameMain;
import com.aldrin.isched.model.SchoolYear;
import com.aldrin.isched.model.Semester;
import com.aldrin.isched.util.ComboBoxList;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ALDRIN B. C.
 */
public class JDialogSchoolYearAU extends javax.swing.JDialog {

    private JFrameMain jFrameRegister;
    private SchoolYear schoolYear = new SchoolYear();
    static String title;
    private SemesterDAOImpl semesterDAOImpl = new SemesterDAOImpl();
    private Semester semester = new Semester();
    private SchoolYearDAOImpl schoolYearDAOImpl = new SchoolYearDAOImpl();

    public JDialogSchoolYearAU(JFrameMain jFrameMain, boolean modal) {
        super(jFrameMain, modal);
        initComponents();
        setTitle("New");
        this.title = "New";
        jButton1.setIcon(new FlatSVGIcon("svg/save.svg", 24, 24));
        jTextFieldSchoolYear.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "SCHOOL YEAR");
        jTextFieldSchoolYear.setText(schoolYear.getSchoolYear());
        comboBoxSemester();
        jButton1.setEnabled(false);

    }

    public JDialogSchoolYearAU(JFrameMain jFrameMain, boolean modal, SchoolYear schoolYear, String title) {
        super(jFrameMain, modal);
        initComponents();
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(187, 187, 187));
        setTitle(title);
        comboBoxSemester();
        this.title = title;
        this.schoolYear = schoolYear;
        jButton1.setIcon(new FlatSVGIcon("svg/edit.svg", 24, 24));
        jButton1.setText(title);
        jTextFieldSchoolYear.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "SCHOOL YEAR");
        jTextFieldSchoolYear.setText(schoolYear.getSchoolYear());
        for (ComboBoxList a : this.semesterDAOImpl.getList()) {
            a.setSelectedId(semesterDAOImpl.getList(), String.valueOf(schoolYear.getSemester().getId()), jComboBoxSemester);
        }
        jButton1.setEnabled(false);
    }

    public JDialogSchoolYearAU(JFrameMain jFrameMain, boolean modal, String title, SchoolYear schoolYear) {
        super(jFrameMain, modal);
        initComponents();
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(187, 187, 187));
        setTitle(title);
        comboBoxSemester();
        this.schoolYear = schoolYear;
        this.title = title;
        jButton1.setIcon(new FlatSVGIcon("svg/delete.svg", 24, 24));
        jButton1.setText(title);
        jTextFieldSchoolYear.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "SCHOOL YEAR");
        jTextFieldSchoolYear.setText(schoolYear.getSchoolYear());
        for (ComboBoxList a : this.semesterDAOImpl.getList()) {
            a.setSelectedId(semesterDAOImpl.getList(), String.valueOf(schoolYear.getSemester().getId()), jComboBoxSemester);
        }
        jButton1.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldSchoolYear = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBoxSemester = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("SCHOOL YEAR:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 30));

        jTextFieldSchoolYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSchoolYearKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldSchoolYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 250, 30));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 140, 30));

        getContentPane().add(jComboBoxSemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 250, 30));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("SEMESTER:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, 30));

        jLabelMessage.setForeground(new java.awt.Color(204, 0, 0));
        jLabelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 340, 30));

        setSize(new java.awt.Dimension(381, 252));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.title.equals("New")) {
            int response = JOptionPane.showConfirmDialog(jFrameRegister, "Are you sure to save " + jTextFieldSchoolYear.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.schoolYear.setId(null);
                this.schoolYear.setSchoolYear(jTextFieldSchoolYear.getText());
                ComboBoxList semesterId = (ComboBoxList) this.jComboBoxSemester.getSelectedItem();
                Semester semester = new Semester();
                semester.setId(semesterId.getId());
                this.schoolYear.setSemester(semester);
                this.schoolYearDAOImpl.addSchoolYear(schoolYear);
                this.dispose();
            }
        } else if (this.title.equals("Update")) {
            int response = JOptionPane.showConfirmDialog(jFrameRegister, "Are you sure to update " + jTextFieldSchoolYear.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.schoolYear.setSchoolYear(jTextFieldSchoolYear.getText());
                ComboBoxList citizenshipId = (ComboBoxList) this.jComboBoxSemester.getSelectedItem();
                Semester semester = new Semester();
                semester.setId(citizenshipId.getId());
                this.schoolYear.setSemester(semester);
                this.schoolYearDAOImpl.updateSchoolYear(schoolYear);
                this.dispose();
            }
        } else if (this.title.equals("Delete")) {
            int response = JOptionPane.showConfirmDialog(jFrameRegister, "Are you sure to delete " + jTextFieldSchoolYear.getText() + " ?", "Save confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                this.schoolYearDAOImpl.deleteSchoolYear(schoolYear);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldSchoolYearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSchoolYearKeyReleased
        if ((schoolYearDAOImpl.isDuplicate(jTextFieldSchoolYear.getText()) == true)) {
            jLabelMessage.setText("Duplicate days are not allowed!");
            jTextFieldSchoolYear.putClientProperty("JComponent.outline", "error");
            jButton1.setEnabled(false);
        } else if ((jTextFieldSchoolYear.getText().isEmpty())) {
            jLabelMessage.setText("Day is required!");
            jTextFieldSchoolYear.putClientProperty("JComponent.outline", "error");
            jButton1.setEnabled(false);
        } else {
            jTextFieldSchoolYear.putClientProperty("JComponent.outline", null);
            jButton1.setEnabled(true);
            jLabelMessage.setText("");
        }
    }//GEN-LAST:event_jTextFieldSchoolYearKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Object> jComboBoxSemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JTextField jTextFieldSchoolYear;
    // End of variables declaration//GEN-END:variables
    private void comboBoxSemester() {
        semesterDAOImpl.comboBoxSemester();
        jComboBoxSemester.removeAllItems();
        for (ComboBoxList a : semesterDAOImpl.getList()) {
            this.jComboBoxSemester.addItem(a);
        }
    }

}
